程序是最诚实的伙伴，从来不会欺骗你，如果他没有按你的预期输出结果，那么一定是你的代码出BUG了。

环境里面创了一对主从的MYSQL实例，但是主节点是ACTIVE，但是3306端口ping不通，从节点是failed状态，反而mysql3306端口能访问。我一开始就怀疑安全组出问题了，但是我居然通过从节点的实例去判断安全组是否正常，而不是去看主节点的安全组，DEBUG了半天才发现主节点的安全组确实出问题了。

为什么会花了半天时间才DEBUG出一个显而易见的问题？回头想想，原来是我为了提高排错的效率，想当然认为过去成功的经验会一直成功。因为上午排查了一个主节点创建成功，从节点没创建出来的问题，是网络少了路由不通导致，但是安全组是没问题的，虽然主从安全组同名，但ID不一样，所以想当然的认为从节点没问题，主节点一定没问题，因为前端调用一直没出现过问题。所以我一直尝试从防火墙，SDN去找出问题。

后来找同事帮忙看看，我跟他打包票说安全组没问题。他捣鼓了个把小时，最后还是不相信我，去查了一把安全组，果然是安全组配错了，脸真疼。反馈给前端程序员，他也不相信这么久的代码会有问题，让我调出api的日志，后来参数显示确实传递了一个错误的安全组ID，他才去review自己的代码。后来发现前端代码确实小概率会出现安全组错误的问题，并且环境里面有少量实例已经错了，只是没被发现。凑巧的是我们连续两个RDS都出问题了。

回到开头，代码很诚实，从来不会欺骗你。避免想当然的去思考问题，我有点矛盾了......
